### ISSUE TITLE
Drop Down Is not showing in django 2.2

### ISSUE THREAD

**Issue by shoaburrashid** [mrts/django-admin-list-filter-dropdown#21]
here is my code: `list_filter = (('question_id',DropdownFilter),('question',DropdownFilter),('qtype',RelatedDropdownFilter), ('difficulties',RelatedDropdownFilter),('subject',RelatedDropdownFilter), ('topic',RelatedDropdownFilter),('sub_topic',RelatedDropdownFilter))`

here is the screenshot:

![Screenshot from 2019-11-06 10-38-49](https://user-images.githubusercontent.com/57428257/68268762-ab1ff180-0081-11ea-8239-2dc14badfaf5.png)

**Comment by mrts** [comment]
It's not showing because there are too little values in your choices, dropdowns are rendered if the choices list contains more than 4 values, see [here](https://github.com/mrts/django-admin-list-filter-dropdown/blob/master/django_admin_listfilter_dropdown/templates/django_admin_listfilter_dropdown/dropdown_filter.html#L5). Can you send a pull request to document this?
